version: "3"
services:
  db:
    image: postgres
    container_name: db
    restart: always
    env_file:
      - .env.test

  node_app:
    build: .
    container_name: node_app
    command: npm run docker-test
    restart: on-failure
    depends_on:
      - db
    env_file:
      - .env.test
