version: "3"
services:
  db:
    image: postgres
    container_name: db
    restart: always
    ports:
      - 5431:5432
    env_file:
      - .env.prod
    volumes:
      - postgres:/var/lib/postgresql/data

  node_app:
    build: .
    container_name: node_app
    command: npm run docker-prod
    restart: on-failure
    ports:
      - 80:5000
    depends_on:
      - db
    env_file:
      - .env.prod

volumes:
  postgres: # create a volume called postgres
